services:
  - type: web
    name: fluttlearn
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: FluttLearn
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: fluttlearn-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fluttlearn-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: fluttlearn-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: fluttlearn-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fluttlearn-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120

databases:
  - name: fluttlearn-db
    plan: starter
    databaseName: fluttlearn
    user: fluttlearn
